---
- debug:
    msg: "Installing Grafana for architecture {{ ansible_architecture }}"

- include_tasks: x86.yml
  when: ansible_architecture == "i386" or ansible_architecture == "x86_64"

- include_tasks: arm.yml
  when: ansible_architecture == "armv7l" or ansible_architecture == "armv6l"

- name: Copy Grafana configuration
  template: src=grafana.ini.j2 dest=/etc/grafana/grafana.ini
  notify: restart grafana
